In [5]:
import pandas as pd
import numpy as np

1. Refer to googleplaystore.csv file and solve following questions
a. Display First 5 records from Dataframe.
b. Display category with highest number of apps registered.
c. What is the average rating for all the apps
d. Display total number of apps which even supports Andriod version 2.3 and up
e. Impute the missing values available in rating column with respective measure
of central tendency.

In [8]:
df = pd.read_csv("googleplaystore.csv")

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [39]:
highest_registers = df["Category"].value_counts()
print(highest_registers.idxmax())

FAMILY

In [43]:
avg_rating = df["Rating"].mean()
print(avg_rating)
df.info()

4.193338315362443
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

In [70]:
count=df[df["Android Ver"] == "2.3 and up"]
count.shape[0]

652

In [90]:
df.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

In [ ]:
val=df["Rating"].mean()
df["Rating"].fillna(val,inplace=True)

In [89]:
df[df["Type"].isna()]
df=df.dropna()

2. Refer to salaries.xlsx file and solve following questions
a. Check head of the dataframe
b. Find out details about no. of entries & no. of columns in the data frame
c. What is the average base pay?
d. What is the highest amount of overtime pay in the dataset?
e. What is the job title of JOSEPH DRISCOLL?
f. How much does JOSEPH DRISCOLL make (including benefits)?
g. How many unique job titles are there?
h. What are the top 5 common jobs?

In [114]:
salD= pd.read_excel("Salaries.xlsx")

In [116]:
salD.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [117]:
salD.shape

(1000, 13)

In [118]:
salD["BasePay"].mean()

np.float64(145663.9982)

In [119]:
salD["OvertimePay"].max()

np.float64(245131.88)

In [121]:
salD[salD["EmployeeName"]=="JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [132]:
un=salD["JobTitle"].unique()
un.shape[0]

113

In [137]:
com=salD["JobTitle"].value_counts()
com.head()

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64