In [1]:
import numpy as np
import pandas as pd

arr=np.array([34,30,48,29,78,30,47,52,60])

In [2]:
arr.mean()

np.float64(45.333333333333336)

In [7]:
s1=pd.Series(arr)
s1

0    34
1    30
2    48
3    29
4    78
5    30
6    47
7    52
8    60
dtype: int64

In [8]:
s1.median()

np.float64(47.0)

In [9]:
dt=pd.read_csv("shoe_sales.csv")

In [11]:
dt.head()

       date   brand  sold_qty
0  9/1/2023    Nike      24.0
1  9/1/2023  Adidas      14.0
2  9/2/2023    Nike      21.0
3  9/2/2023  Adidas      12.0
4  9/3/2023    Nike      18.0

In [12]:
dt.shape

(60, 3)

In [13]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      60 non-null     object
 1   brand     60 non-null     object
 2   sold_qty  58 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.5+ KB

In [22]:
dt.isna().sum()

date        0
brand       0
sold_qty    0
dtype: int64

In [16]:
dt[dt["sold_qty"].isna()==True]

         date brand  sold_qty
32  9/17/2023  Nike       NaN
48  9/25/2023  Nike       NaN

In [17]:
avg=dt["sold_qty"].mean()

In [19]:
avg1=dt[dt["brand"]=="Nike"]["sold_qty"].mean()
avg1

np.float64(19.642857142857142)

In [21]:
dt["sold_qty"]=dt["sold_qty"].fillna(avg1)