In [4]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.2.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.4.2)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.0 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.0 MB 2.5 MB/s eta 0:00:03
   ----- ---------------------------------- 1.0/8.0 MB 1.8 MB/s eta 0:00:04
   ------- -------------------------------- 1.6/8.0 MB 2.1 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.0 MB 2.2 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.0 MB 2.4 MB/s eta 0:00:03
   ----------------- ---------------------- 3.4/8.0 MB 2.5 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.0 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 4.7/8.0 MB 2.7 MB/s eta 0:00:02
   --------------------------- ------------ 5.5/8.0 MB 2.8 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.0 MB 2.8 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 2.9 MB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 2.8 MB/s  0:00:02
Downloading scipy-1.17.1-cp313-cp313-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 3.2 MB/s eta 0:00:12
   - -------------------------------------- 1.0/36.5 MB 2.7 MB/s eta 0:00:14
   -- ------------------------------------- 1.8/36.5 MB 3.0 MB/s eta 0:00:12
   -- ------------------------------------- 2.4/36.5 MB 3.1 MB/s eta 0:00:12
   --- ------------------------------------ 2.9/36.5 MB 2.8 MB/s eta 0:00:12
   --- ------------------------------------ 3.4/36.5 MB 2.9 MB/s eta 0:00:12
   ---- ----------------------------------- 4.2/36.5 MB 2.8 MB/s eta 0:00:12
   ----- ---------------------------------- 4.7/36.5 MB 2.8 MB/s eta 0:00:12
   ----- ---------------------------------- 5.2/36.5 MB 2.8 MB/s eta 0:00:12
   ------ --------------------------------- 5.8/36.5 MB 2.8 MB/s eta 0:00:11
   ------- -------------------------------- 6.6/36.5 MB 2.8 MB/s eta 0:00:11
   ------- -------------------------------- 7.1/36.5 MB 2.8 MB/s eta 0:00:11
   -------- ------------------------------- 7.3/36.5 MB 2.8 MB/s eta 0:00:11
   -------- ------------------------------- 8.1/36.5 MB 2.8 MB/s eta 0:00:11
   --------- ------------------------------ 8.7/36.5 MB 2.8 MB/s eta 0:00:10
   ---------- ----------------------------- 9.4/36.5 MB 2.8 MB/s eta 0:00:10
   ---------- ----------------------------- 10.0/36.5 MB 2.8 MB/s eta 0:00:10
   ----------- ---------------------------- 10.5/36.5 MB 2.8 MB/s eta 0:00:10
   ----------- ---------------------------- 10.7/36.5 MB 2.8 MB/s eta 0:00:10
   ------------ --------------------------- 11.3/36.5 MB 2.7 MB/s eta 0:00:10
   ------------ --------------------------- 11.8/36.5 MB 2.7 MB/s eta 0:00:10
   ------------- -------------------------- 12.3/36.5 MB 2.7 MB/s eta 0:00:10
   -------------- ------------------------- 12.8/36.5 MB 2.7 MB/s eta 0:00:09
   -------------- ------------------------- 13.4/36.5 MB 2.7 MB/s eta 0:00:09
   --------------- ------------------------ 14.2/36.5 MB 2.7 MB/s eta 0:00:09
   ---------------- ----------------------- 14.7/36.5 MB 2.7 MB/s eta 0:00:09
   ---------------- ----------------------- 15.2/36.5 MB 2.7 MB/s eta 0:00:08
   ----------------- ---------------------- 15.7/36.5 MB 2.7 MB/s eta 0:00:08
   ----------------- ---------------------- 16.3/36.5 MB 2.7 MB/s eta 0:00:08
   ------------------ --------------------- 16.8/36.5 MB 2.7 MB/s eta 0:00:08
   ------------------ --------------------- 17.0/36.5 MB 2.7 MB/s eta 0:00:08
   ------------------- -------------------- 17.6/36.5 MB 2.6 MB/s eta 0:00:08
   ------------------- -------------------- 18.1/36.5 MB 2.6 MB/s eta 0:00:08
   -------------------- ------------------- 18.6/36.5 MB 2.6 MB/s eta 0:00:07
   -------------------- ------------------- 19.1/36.5 MB 2.6 MB/s eta 0:00:07
   --------------------- ------------------ 19.7/36.5 MB 2.6 MB/s eta 0:00:07
   ---------------------- ----------------- 20.2/36.5 MB 2.6 MB/s eta 0:00:07
   ---------------------- ----------------- 20.2/36.5 MB 2.6 MB/s eta 0:00:07
   ---------------------- ----------------- 20.7/36.5 MB 2.5 MB/s eta 0:00:07
   ----------------------- ---------------- 21.2/36.5 MB 2.5 MB/s eta 0:00:07
   ------------------------ --------------- 22.0/36.5 MB 2.6 MB/s eta 0:00:06
   ------------------------ --------------- 22.5/36.5 MB 2.6 MB/s eta 0:00:06
   ------------------------- -------------- 23.1/36.5 MB 2.6 MB/s eta 0:00:06
   -------------------------- ------------- 23.9/36.5 MB 2.6 MB/s eta 0:00:05
   -------------------------- ------------- 24.4/36.5 MB 2.6 MB/s eta 0:00:05
   --------------------------- ------------ 25.2/36.5 MB 2.6 MB/s eta 0:00:05
   ---------------------------- ----------- 25.7/36.5 MB 2.6 MB/s eta 0:00:05
   ----------------------------- ---------- 26.5/36.5 MB 2.6 MB/s eta 0:00:04
   ----------------------------- ---------- 27.0/36.5 MB 2.6 MB/s eta 0:00:04
   ----------------------------- ---------- 27.3/36.5 MB 2.6 MB/s eta 0:00:04
   ------------------------------ --------- 27.8/36.5 MB 2.6 MB/s eta 0:00:04
   ------------------------------- -------- 28.6/36.5 MB 2.6 MB/s eta 0:00:04
   ------------------------------- -------- 29.1/36.5 MB 2.6 MB/s eta 0:00:03
   -------------------------------- ------- 29.9/36.5 MB 2.6 MB/s eta 0:00:03
   --------------------------------- ------ 30.7/36.5 MB 2.7 MB/s eta 0:00:03
   ---------------------------------- ----- 31.2/36.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------------- ---- 32.0/36.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------------- ---- 32.5/36.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.5 MB 2.7 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.5 MB 2.6 MB/s eta 0:00:02
   ------------------------------------ --- 33.3/36.5 MB 2.6 MB/s eta 0:00:02
   ------------------------------------ --- 33.6/36.5 MB 2.6 MB/s eta 0:00:02
   ------------------------------------- -- 33.8/36.5 MB 2.6 MB/s eta 0:00:02
   ------------------------------------- -- 34.1/36.5 MB 2.6 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 34.9/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 2.3 MB/s  0:00:15
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, scikit-learn

   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]
   ------------- -------------------------- 1/3 [scipy]

In [50]:
data = pd.read_csv("cars93.csv")
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [11]:
data.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [51]:
data["AirBags"]=data["AirBags"].fillna(data["AirBags"].mode()[0])

In [52]:
data["Luggage.room"]=data["Luggage.room"].fillna(data["Luggage.room"].mean())

In [53]:
data.dropna(inplace=True)

In [54]:
data.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le=LabelEncoder()

In [23]:
data["Type"] = le.fit_transform(data["Type"])

In [24]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,3,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,2,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,0,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,2,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,2,30.0,22,Driver only,208,4,27.0,13.0

In [35]:
from sklearn.preprocessing import OrdinalEncoder
od=OrdinalEncoder(categories=[['Compact', 'Small', 'Midsize','Sporty', 'Large', 'Van']])

In [39]:
data["Type"]=od.fit_transform(data[["Type"]]).astype('int')

In [40]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,1,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,2,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,0,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,2,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,2,30.0,22,Driver only,208,4,27.0,13.0

In [47]:
oh = OneHotEncoder()
result = oh.fit_transform(data[["AirBags"]]).toarray()
result=pd.DataFrame(result , columns=["Driver only","Driver & passenger","none"])
data = pd.concat([data,result],axis = 1)
data.drop("AirBags",axis = 1, inplace=True )

In [49]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room,Driver only,Driver & passenger,Driver only,Driver & passenger,none
0,Acura,Integra,1.0,15.9,25.0,140.0,5.0,26.5,11.0,0.0,1.0,0.0,1.0,0.0
1,Acura,Legend,2.0,33.9,18.0,200.0,5.0,30.0,15.0,1.0,0.0,1.0,0.0,0.0
2,Audi,90,0.0,29.1,20.0,172.0,5.0,28.0,14.0,0.0,1.0,0.0,1.0,0.0
3,Audi,100,2.0,37.7,19.0,172.0,6.0,31.0,17.0,1.0,0.0,1.0,0.0,0.0
4,BMW,535i,2.0,30.0,22.0,208.0,4.0,27.0,13.0,0.0,1.0,0.0,1.0,0.0

In [56]:
data = pd.get_dummies(data,columns=["AirBags"],dtype="int")

In [57]:
data.head()

,Manufacturer,Model,Type,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room,AirBags_Driver & Passenger,AirBags_Driver only
0,Acura,Integra,Small,15.9,25,140,5,26.5,11.0,0,1
1,Acura,Legend,Midsize,33.9,18,200,5,30.0,15.0,1,0
2,Audi,90,Compact,29.1,20,172,5,28.0,14.0,0,1
3,Audi,100,Midsize,37.7,19,172,6,31.0,17.0,1,0
4,BMW,535i,Midsize,30.0,22,208,4,27.0,13.0,0,1